/**
 * Zinnen voor Marble — natuurlijk Nederlands (geen vertaling uit het Spaans).
 */
const NlPhrases = {
  compliments: [
    '{name}, je straalt vandaag echt. Dat zie je meteen.',
    '{name}, je ziet er verzorgd en zelfverzekerd uit.',
    'Wat een fijne uitstraling heb je vandaag, {name}.',
    '{name}, je ogen staan mooi op scherp.',
    'Je hebt iets sympathieks over je heen, {name}.',
    '{name}, je ziet er fris en opgewekt uit.',
    'Je straalt warmte uit, {name}. Dat komt goed over.',
    '{name}, je hebt vandaag echt iets bijzonders.',
    'Ik vind je houding sterk, {name}. Dat tilt alles op.',
    '{name}, je ziet er natuurlijk mooi uit. Zonder moeite.',
    'Je hebt charme, {name}. Dat is niet te kopen.',
    '{name}, je straalt rust en zelfvertrouwen uit.',
    'Wat een prettige energie heb je vandaag, {name}.',
    '{name}, je ziet er echt goed uit. Serieus.',
    'Je hebt vandaag iets dat blijft hangen, {name}. In positieve zin.',
    '{name}, je uitstraling is warm en uitnodigend.',
    '{name}, je straalt zoiets van: ik heb dit onder controle.',
    'Je ziet er vandaag echt op je gemak uit, {name}.',
    '{name}, je hebt een open blik. Dat staat je goed.',
    'Je straalt vandaag echt positieve energie uit, {name}.',
    '{name}, je ziet er verzorgd uit. Alsof je weet wat je doet.',
    'Wat een mooie rust straal je uit, {name}.',
    '{name}, je hebt iets aantrekkelijks over je heen. Echt waar.',
    'Je ziet er vandaag stralend uit, {name}.',
    '{name}, je hebt pit. En dat past bij je.',
  ],
  look: [
    '{name}, je ziet er vandaag echt goed uit.',
    'Je gezicht staat lekker open, {name}.',
    '{name}, je straalt positieve energie uit.',
    'Je ziet er ontspannen en zelfverzekerd uit, {name}.',
    '{name}, je uitdrukking past mooi bij wat je draagt.',
    'Alles klopt vandaag, {name}. Echt waar.',
    '{name}, je bent klaar om de dag te pakken.',
    'Je ziet er fris en uitgerust uit, {name}.',
    '{name}, het licht valt mooi op je gezicht.',
    'Je straalt rust uit, {name}. Dat staat je goed.',
    '{name}, je ziet er verzorgd en op je gemak uit.',
    'Je hebt vandaag een sterke uitstraling, {name}.',
    '{name}, je ziet er gemotiveerd en positief uit.',
    'Je straalt vertrouwen uit, {name}. Dat is te zien.',
    '{name}, je gezicht en je kleding passen mooi bij elkaar.',
    'Je ziet er vandaag echt op je best uit, {name}.',
    '{name}, je hebt een open, vriendelijke blik.',
    'Je straalt iets uit waar je blij van wordt, {name}.',
    '{name}, je ziet er verzorgd uit. Punt.',
    'Je hebt vandaag echt goede energie, {name}.',
  ],
  outfit: [
    '{name}, wat je draagt staat je echt goed.',
    'De combinatie die je aanhebt werkt heel goed, {name}.',
    '{name}, je kleding zit mooi op elkaar.',
    'Je hebt duidelijk nagedacht over je kleding, {name}.',
    '{name}, deze combinatie past bij je.',
    'Wat je vandaag aanhebt heeft karakter, {name}.',
    '{name}, je kleding en jij vormen een mooi geheel.',
    'De verhoudingen in je kleding kloppen, {name}.',
    '{name}, je ziet er stijlvol uit zonder te veel poespas.',
    'Je kleding vertelt een samenhangend verhaal, {name}.',
    '{name}, deze stijl is modern en past bij je.',
    'Simpel maar met pit. Dat werkt bij jou, {name}.',
    '{name}, je hebt een mooie balans in je kleding gevonden.',
    'Je kleding straalt zelfvertrouwen uit, {name}.',
    '{name}, je kleuren en stijl passen bij elkaar.',
    'Wat je aanhebt voelt doordacht aan, {name}.',
    '{name}, je kleding is netjes zonder saai te zijn.',
    'Je hebt vandaag goed gekozen, {name}. Dat zie je.',
    '{name}, je combinatie is fris en verzorgd.',
    'Je kleding ondersteunt je uitstraling, {name}.',
  ],
  styleGeneral: [
    '{name}, je stijl voelt vandaag authentiek.',
    'Er zit samenhang in wat je draagt, {name}.',
    '{name}, je ziet er verzorgd uit zonder te proberen.',
    'Je stijl is vandaag licht en zelfverzekerd, {name}.',
    '{name}, de details laten zien dat je om jezelf geeft.',
    'Er zit iets heel jij in je kleding, {name}.',
    '{name}, je hoeft niet op te vallen om indruk te maken.',
    'Je zit lekker in je stijl, {name}. Dat zie je meteen.',
    '{name}, je uitstraling is vandaag helemaal af.',
    'Persoonlijkheid zie je in elke keuze, {name}.',
    '{name}, je kleding en je houding passen goed bij elkaar.',
    'Je stijl voelt warm en toegankelijk, {name}.',
    '{name}, je hebt een eigen stijl. Dat is waardevol.',
    'Je ziet er verzorgd uit zonder te veel moeite, {name}.',
    '{name}, je stijl is rustig maar met karakter.',
  ],
  neutralLook: [
    'Neutrale tinten staan je prachtig, {name}. Heel chic.',
    '{name}, deze ingetogen stijl heeft klasse.',
    'Zachte kleuren staan je goed, {name}.',
    '{name}, minder is soms meer. En jij bewijst het.',
    'Een rustig palet, maar een sterk resultaat, {name}.',
    '{name}, neutrale kleuren geven je een elegante uitstraling.',
    'Ingetogen, maar met pit. Dat past bij jou, {name}.',
  ],
  date: [
    '{name}, je ziet er uitnodigend en verzorgd uit.',
    'Voor een afspraakje zit je goed, {name}.',
    '{name}, je hebt iets speciaals zonder overdreven te zijn.',
    'Je ziet er verzorgd uit zonder te veel moeite, {name}.',
    '{name}, je maakt zeker een goede indruk.',
    'Voor uitgaan heb je de juiste balans, {name}.',
    '{name}, je straalt iets uit waar je blij van wordt.',
    'Je ziet er charmant en op je gemak uit, {name}.',
    '{name}, voor een date ben je helemaal klaar.',
    'Je hebt iets uitnodigends over je heen, {name}.',
  ],
  advice: [
    '{name}, vertrouw op wat je draagt. Het werkt.',
    'Ik zou bij deze stijl blijven, {name}. Het past bij je.',
    '{name}, met deze basis kun je bijna alles combineren.',
    'Een glimlach maakt je stijl helemaal af, {name}.',
    '{name}, ik zou niet veel veranderen. Je zit goed.',
    'Twijfel je? Houd wat je aanhebt, {name}. Het staat je.',
    '{name}, minder is meer. En jij hebt al genoeg pit.',
    '{name}, blijf bij wat je nu draagt. Dat is slim.',
    'Mijn tip: glimlach erbij en je bent klaar, {name}.',
    '{name}, verander niet te veel. Je zit al goed.',
  ],
  styleVibe: [
    '{name}, je stijl is vandaag fris en actueel.',
    'Je bent casual maar verzorgd, {name}. Dat werkt altijd.',
    '{name}, je uitstraling is helder en doordacht.',
    'Je mengt ontspannen en netjes mooi, {name}.',
    '{name}, je ziet er modern uit zonder hard te schreeuwen.',
    'Je hebt een aantrekkelijke, eigentijdse stijl, {name}.',
    '{name}, je kleding en je houding vullen elkaar aan.',
    'Je straalt iets moderns en rustigs uit, {name}.',
    '{name}, je stijl is verzorgd maar niet stijf.',
    'Je hebt een fijne, eigentijdse uitstraling, {name}.',
  ],
  thanks: [
    'Graag gedaan, {name}!',
    'Geen probleem, {name}! Vraag gerust weer.',
    'Met plezier, {name}! Kom gerust terug.',
    'Altijd leuk, {name}!',
    'Voor niets, {name}!',
  ],
  bye: [
    'Tot ziens, {name}! Fijne dag.',
    'Doei, {name}! Tot de volgende keer.',
    'Later, {name}! Je weet waar je me vindt.',
    'Dag {name}! Kom gerust terug.',
    'Tot snel, {name}!',
  ],
  colorAlso: [
    'Er zit ook een beetje {color} in. Dat past erbij.',
    'Ik zie ook {color} terug. Mooi samen.',
    'Er zit ook {color} in. Dat rondt het af.',
    'Ik merk ook {color}. Dat combineert mooi.',
    'Je hebt ook {color} in je kleding. Dat past goed.',
  ],
};
