/**
 * Frases extra para más variedad (se combinan con i18n).
 */
const PhrasePools = {
  es: {
    compliments: [
      '{name}, hoy tienes un brillo natural que enamora.',
      'Si el estilo tuviera premio, {name}, tú ganarías hoy.',
      '{name}, hay algo en tu look que transmite buena vibra.',
      'Me encanta tu actitud, {name}. Se nota en cada detalle.',
      '{name}, vas con una seguridad que eleva todo lo que llevas.',
      'Hoy desprendes carisma, {name}. De verdad.',
      '{name}, tu imagen de hoy es fresca y con mucho encanto.',
      'Tienes un punto desenfadado muy bonito, {name}.',
      '{name}, luces auténtica y eso se valora muchísimo.',
      '¡{name}! Tu estilo habla por ti y dice cosas buenas.',
      '{name}, hoy tienes ese algo que hace memorable cualquier look.',
      'Si pudiera votar, {name}, tu estilo ganaría por goleada.',
      '{name}, irradias buen gusto sin pretenderlo. Eso es talento.',
      'Me quedo con tu energía hoy, {name}. Es contagiosa.',
      '{name}, tienes un estilo que abraza sin esfuerzo.',
      'Hoy luces con una seguridad silenciosa muy bonita, {name}.',
    ],
    look: [
      '{name}, hoy tienes muy buena presencia frente a la cámara.',
      'Te ves relajada y segura, {name}. Eso se nota.',
      '{name}, tu expresión acompaña muy bien tu outfit.',
      'Hay armonía en tu imagen hoy, {name}. Me gusta.',
      '{name}, transmites una energía positiva y se ve.',
      'Tu look de hoy tiene carácter, {name}. Muy bien.',
      '{name}, te ves lista para conquistar el día.',
      'Hoy tienes un aire despierto y favorecedor, {name}.',
      '{name}, tu imagen de hoy es clara y muy favorecedora.',
      'Se te ve bien la luz de hoy, {name}. Todo encaja.',
      '{name}, tienes buena cara y eso lo eleva todo.',
      'Tu presencia en cámara es fuerte y amable, {name}.',
      '{name}, hoy transmites calma y eso siempre suma.',
      'Te ves renovada y con ganas, {name}. Se nota un montón.',
    ],
    outfit: [
      '{name}, la combinación que llevas funciona muy bien.',
      'Se nota que pensaste el conjunto, {name}. Buen ojo.',
      '{name}, tu outfit tiene personalidad sin exagerar.',
      'Lo que llevas puesto hoy encaja contigo, {name}.',
      '{name}, has encontrado un equilibrio muy bonito.',
      'Tu ropa de hoy cuenta una historia coherente, {name}.',
      '{name}, el conjunto es moderno y te sienta bien.',
      '{name}, lo que llevas hoy tiene ritmo y buen criterio.',
      'Tu outfit tiene flow, {name}. Me convence totalmente.',
      '{name}, la proporción de tu look es muy acertada.',
      'Hoy vestiste con intención, {name}, y se nota.',
      '{name}, tu ropa y tú estáis en la misma sintonía.',
      'El conjunto es simple pero con chispa, {name}. Me gusta.',
    ],
    styleGeneral: [
      '{name}, el conjunto tiene ritmo y buen gusto.',
      'Hoy tu estilo se siente auténtico, {name}.',
      '{name}, hay coherencia en lo que llevas y se agradece.',
      'Tu look transmite seguridad sin esfuerzo, {name}.',
      '{name}, se nota cuidado en los detalles. Muy bien.',
      'Me gusta la vibra general de tu outfit, {name}.',
      '{name}, hoy tu estilo se siente ligero y seguro.',
      'Hay algo muy "tú" en lo que llevas, {name}.',
      '{name}, tu look no necesita exagerar para destacar.',
      'Se nota personalidad en cada elección, {name}.',
      '{name}, vas cómoda con tu estilo y eso se ve.',
      'Tu imagen de hoy es redonda, {name}. Bien hecho.',
    ],
    neutralLook: [
      'Los neutros te quedan de maravilla hoy, {name}. Muy chic.',
      '{name}, este look sobrio tiene mucha clase.',
      'Paleta neutra y resultado elegante, {name}.',
      '{name}, menos es más y tú lo demuestras.',
      'Los tonos suaves te favorecen muchísimo, {name}.',
    ],
    date: [
      '{name}, vas con un look que invita a sonreír.',
      'Para salir y sentirte bien, {name}, vas ideal.',
      '{name}, tienes ese toque especial sin ir overdressed.',
      '{name}, para una cita vas impecable sin parecer forzada.',
      'Ese look dice "me importo" sin decir demasiado, {name}.',
      '{name}, vas a dejar buena impresión, seguro.',
      'Para quedar tienes el equilibrio perfecto, {name}.',
    ],
    advice: [
      '{name}, un accesorio sencillo podría rematar el look.',
      'Yo mantendría esta línea, {name}. Te define bien.',
      '{name}, con esa base, casi cualquier extra funciona.',
      'Un buen peinado y ya tienes el combo ganador, {name}.',
      '{name}, no cambiaría mucho: vas por buen camino.',
      'Si dudas, quédate con lo que llevas, {name}. Funciona.',
      'Menos capas y más actitud, {name}. Ya lo tienes.',
    ],
    styleVibe: [
      '{name}, hoy tu estilo se siente actual y limpio.',
      'Tienes un punto cool sin perder elegancia, {name}.',
      '{name}, tu imagen es clara y con intención.',
      '{name}, hoy tu estilo es fresco y con carácter.',
      'Tienes un vibe moderno muy atractivo, {name}.',
      '{name}, combinas casual y cuidado a la perfección.',
      'Tu estética de hoy es limpia y con personalidad, {name}.',
    ],
    thanks: [
      '¡De nada, {name}! Me encanta ayudarte.',
      '¡Para eso estoy, {name}! Cuando quieras.',
      '¡Un placer, {name}! Pregunta lo que necesites.',
    ],
    bye: [
      '¡Hasta pronto, {name}! Siempre es un gusto.',
      '¡Nos vemos, {name}! Que tengas un día genial.',
      '¡Chao, {name}! Vuelve cuando quieras un cumplido.',
    ],
    colorAlso: [
      'Además veo un toque de {color} que combina muy bien.',
      'Hay un matiz de {color} que redondea el conjunto.',
      'Noto también {color} y queda muy armónico.',
    ],
  },
  en: {
    compliments: [
      '{name}, you have a natural glow today.',
      'If style had awards, {name}, you would win today.',
      '{name}, your look sends really good vibes.',
      'I love your attitude, {name}. It shows in every detail.',
      '{name}, you wear confidence and it elevates everything.',
      'You are radiating charisma today, {name}.',
      '{name}, your image feels fresh and charming.',
      'You have a lovely effortless touch, {name}.',
      '{name}, you look authentic and that matters.',
      '{name}! Your style speaks for you — and it says great things.',
      '{name}, you have that something that makes any look memorable.',
      'If I could vote, {name}, your style would win by a landslide.',
      '{name}, you radiate good taste without trying. That is a gift.',
      'I am keeping your energy today, {name}. It is contagious.',
      '{name}, your style feels effortless and warm.',
      'You have a quiet confidence today that looks great, {name}.',
    ],
    look: [
      '{name}, you have great presence on camera today.',
      'You look relaxed and confident, {name}. It shows.',
      '{name}, your expression matches your outfit really well.',
      'There is harmony in your look today, {name}. I like it.',
      '{name}, you are giving positive energy and it shows.',
      'Your look has character today, {name}. Well done.',
      '{name}, you look ready to own the day.',
      'You have a bright, flattering vibe today, {name}.',
      '{name}, your image today is clear and very flattering.',
      'The light suits you today, {name}. Everything clicks.',
      '{name}, you look well-rested and that elevates everything.',
      'Your camera presence is strong and kind, {name}.',
      '{name}, you are giving calm energy and it works.',
      'You look refreshed and motivated, {name}. It really shows.',
    ],
    outfit: [
      '{name}, the combination you are wearing works really well.',
      'You clearly thought about this outfit, {name}. Great eye.',
      '{name}, your outfit has personality without trying too hard.',
      'What you are wearing fits you today, {name}.',
      '{name}, you found a really nice balance.',
      'Your clothes tell a coherent story today, {name}.',
      '{name}, the outfit is modern and suits you.',
      '{name}, what you are wearing today has rhythm and taste.',
      'Your outfit has flow, {name}. I am convinced.',
      '{name}, the proportions of your look are spot on.',
      'You dressed with intention today, {name}, and it shows.',
      '{name}, your clothes and you are in sync.',
      'The outfit is simple but has spark, {name}. I like it.',
    ],
    styleGeneral: [
      '{name}, the outfit has rhythm and good taste.',
      'Your style feels authentic today, {name}.',
      '{name}, there is coherence in what you are wearing.',
      'Your look feels confident without effort, {name}.',
      '{name}, the details show care. Nicely done.',
      'I like the overall vibe of your outfit, {name}.',
      '{name}, your style feels light and confident today.',
      'There is something very "you" in what you are wearing, {name}.',
      '{name}, your look does not need to shout to stand out.',
      'Personality shows in every choice, {name}.',
      '{name}, you look comfortable in your style and it shows.',
      'Your image today feels complete, {name}. Well done.',
    ],
    neutralLook: [
      'Neutrals look wonderful on you today, {name}. Very chic.',
      '{name}, this understated look has real class.',
      'Neutral palette, elegant result, {name}.',
      '{name}, less is more and you prove it.',
      'Soft tones suit you so well, {name}.',
    ],
    date: [
      '{name}, you look inviting and easy to smile at.',
      'For going out and feeling great, {name}, you are spot on.',
      '{name}, you have something special without being overdressed.',
      '{name}, for a date you look polished without trying too hard.',
      'That look says "I care" without saying too much, {name}.',
      '{name}, you will make a great impression, I am sure.',
      'For going out you have the perfect balance, {name}.',
    ],
    advice: [
      '{name}, a simple accessory could finish the look.',
      'I would keep this direction, {name}. It defines you well.',
      '{name}, with this base, almost any accent would work.',
      'A good hair day and you have the winning combo, {name}.',
      '{name}, I would not change much: you are on the right track.',
      'If in doubt, keep what you are wearing, {name}. It works.',
      'Less layering, more attitude, {name}. You already have it.',
    ],
    styleVibe: [
      '{name}, your style feels current and clean today.',
      'You are cool without losing elegance, {name}.',
      '{name}, your image is clear and intentional.',
      '{name}, your style today feels fresh and bold.',
      'You have a very attractive modern vibe, {name}.',
      '{name}, you blend casual and polished perfectly.',
      'Your look today is clean and full of personality, {name}.',
    ],
    thanks: [
      "You're welcome, {name}! Happy to help.",
      'Any time, {name}! Just ask.',
      'My pleasure, {name}! Come back whenever.',
    ],
    bye: [
      'See you soon, {name}! Always a pleasure.',
      'Bye, {name}! Have an amazing day.',
      'Later, {name}! Come back for another compliment.',
    ],
    colorAlso: [
      'I also see a touch of {color} that pairs nicely.',
      'There is a hint of {color} rounding off the outfit.',
      'I notice some {color} too — very harmonious.',
    ],
  },
  nl: {
    compliments: [
      '{name}, je hebt vandaag een natuurlijke gloed.',
      'Als stijl prijzen had, {name}, dan won jij vandaag.',
      '{name}, je look straalt echt goede vibes uit.',
      'Ik hou van je houding, {name}. Dat zie je in elk detail.',
      '{name}, je draagt zelfvertrouwen en dat tilt alles op.',
      'Je straalt charisma uit vandaag, {name}.',
      '{name}, je uitstraling voelt fris en charmant.',
      'Je hebt iets moeiteloos moois, {name}.',
      '{name}, je ziet er authentiek uit en dat telt.',
      '{name}! Je stijl spreekt voor je — en het klinkt goed.',
      '{name}, je hebt vandaag iets dat elke look onvergetelijk maakt.',
      'Als ik kon stemmen, {name}, zou je stijl met overtuiging winnen.',
      '{name}, je straalt goede smaak uit zonder moeite. Dat is talent.',
      'Ik blijf hangen aan je energie vandaag, {name}. Het is aanstekelijk.',
      '{name}, je stijl voelt moeiteloos en warm aan.',
      'Je hebt vandaag een rustige zelfverzekerdheid die goed staat, {name}.',
    ],
    look: [
      '{name}, je hebt vandaag veel uitstraling voor de camera.',
      'Je ziet er ontspannen en zelfverzekerd uit, {name}.',
      '{name}, je gezichtsuitdrukking past goed bij je outfit.',
      'Er is harmonie in je look vandaag, {name}. Mooi.',
      '{name}, je geeft positieve energie en dat is te zien.',
      'Je look heeft karakter vandaag, {name}. Goed gedaan.',
      '{name}, je bent klaar om de dag te pakken.',
      'Je hebt een frisse, flatterende vibe vandaag, {name}.',
      '{name}, je beeld vandaag is helder en heel flatterend.',
      'Het licht staat je goed vandaag, {name}. Alles klopt.',
      '{name}, je ziet er uitgerust uit en dat tilt alles op.',
      'Je uitstraling op camera is sterk en vriendelijk, {name}.',
      '{name}, je straalt rustige energie uit en dat werkt.',
      'Je ziet er verfrist en gemotiveerd uit, {name}. Dat is duidelijk.',
    ],
    outfit: [
      '{name}, de combinatie die je draagt werkt heel goed.',
      'Je hebt duidelijk nagedacht over dit outfit, {name}.',
      '{name}, je outfit heeft persoonlijkheid zonder te veel.',
      'Wat je draagt past bij je vandaag, {name}.',
      '{name}, je hebt een mooie balans gevonden.',
      'Je kleding vertelt vandaag een coherent verhaal, {name}.',
      '{name}, het outfit is modern en staat je goed.',
      '{name}, wat je vandaag draagt heeft ritme en smaak.',
      'Je outfit heeft flow, {name}. Ik ben overtuigd.',
      '{name}, de verhoudingen van je look kloppen helemaal.',
      'Je hebt vandaag met opzet gekleed, {name}, en dat zie je.',
      '{name}, je kleren en jij zitten op één lijn.',
      'Het outfit is simpel maar met pit, {name}. Ik vind het leuk.',
    ],
    styleGeneral: [
      '{name}, het outfit heeft ritme en goede smaak.',
      'Je stijl voelt vandaag authentiek, {name}.',
      '{name}, er is samenhang in wat je draagt.',
      'Je look straalt moeiteloos vertrouwen uit, {name}.',
      '{name}, de details tonen zorg. Netjes gedaan.',
      'Ik hou van de algemene vibe van je outfit, {name}.',
      '{name}, je stijl voelt vandaag licht en zelfverzekerd.',
      'Er zit iets heel "jij" in wat je draagt, {name}.',
      '{name}, je look hoeft niet te schreeuwen om op te vallen.',
      'Persoonlijkheid zie je in elke keuze, {name}.',
      '{name}, je zit lekker in je stijl en dat is te zien.',
      'Je beeld vandaag voelt compleet, {name}. Goed gedaan.',
    ],
    neutralLook: [
      'Neutrale tinten staan je vandaag prachtig, {name}. Heel chic.',
      '{name}, deze ingetogen look heeft echte klasse.',
      'Neutraal palet, elegant resultaat, {name}.',
      '{name}, less is more en jij bewijst het.',
      'Zachte tonen staan je zo goed, {name}.',
    ],
    date: [
      '{name}, je ziet er uitnodigend en spontaan uit.',
      'Om uit te gaan en je goed te voelen, {name}, zit je goed.',
      '{name}, je hebt iets speciaals zonder overdressed te zijn.',
      '{name}, voor een date zie je verzorgd uit zonder te veel moeite.',
      'Die look zegt "ik geef om mezelf" zonder te veel woorden, {name}.',
      '{name}, je maakt zeker een goede indruk.',
      'Om uit te gaan heb je de perfecte balans, {name}.',
    ],
    advice: [
      '{name}, een simpel accessoire zou de look afmaken.',
      'Ik zou deze lijn aanhouden, {name}. Het past bij je.',
      '{name}, met deze basis werkt bijna elke accent.',
      'Een goede hair day en je hebt de winnende combo, {name}.',
      '{name}, ik zou niet veel veranderen: je zit goed.',
      'Twijfel je? Houd wat je draagt, {name}. Het werkt.',
      'Minder lagen, meer attitude, {name}. Dat heb je al.',
    ],
    styleVibe: [
      '{name}, je stijl voelt vandaag actueel en clean.',
      'Je bent cool zonder elegantie te verliezen, {name}.',
      '{name}, je beeld is helder en met intentie.',
      '{name}, je stijl voelt vandaag fris en krachtig.',
      'Je hebt een heel aantrekkelijke moderne vibe, {name}.',
      '{name}, je mixt casual en verzorgd perfect.',
      'Je look vandaag is clean en vol persoonlijkheid, {name}.',
    ],
    thanks: [
      'Graag gedaan, {name}! Ik help je graag.',
      'Altijd welkom, {name}! Vraag maar.',
      'Met plezier, {name}! Kom gerust terug.',
    ],
    bye: [
      'Tot ziens, {name}! Altijd leuk.',
      'Doei, {name}! Fijne dag gewenst.',
      'Later, {name}! Kom terug voor een compliment.',
    ],
    colorAlso: [
      'Ik zie ook een vleugje {color} dat mooi combineert.',
      'Er zit een hint {color} in die het geheel rond maakt.',
      'Ik merk ook {color} op — heel harmonieus.',
    ],
  },
};
