/**
 * Frases extra para más variedad (se combinan con i18n).
 */
const PhrasePools = {
  es: {
    compliments: [
      '{name}, hoy tienes un brillo natural que enamora.',
      'Si el estilo tuviera premio, {name}, tú ganarías hoy.',
      '{name}, hay algo en tu look que transmite buena vibra.',
      'Me encanta tu actitud, {name}. Se nota en cada detalle.',
      '{name}, vas con una seguridad que eleva todo lo que llevas.',
      'Hoy desprendes carisma, {name}. De verdad.',
      '{name}, tu imagen de hoy es fresca y con mucho encanto.',
      'Tienes un punto desenfadado muy bonito, {name}.',
      '{name}, luces auténtica y eso se valora muchísimo.',
      '¡{name}! Tu estilo habla por ti y dice cosas buenas.',
    ],
    look: [
      '{name}, hoy tienes muy buena presencia frente a la cámara.',
      'Te ves relajada y segura, {name}. Eso se nota.',
      '{name}, tu expresión acompaña muy bien tu outfit.',
      'Hay armonía en tu imagen hoy, {name}. Me gusta.',
      '{name}, transmites una energía positiva y se ve.',
      'Tu look de hoy tiene carácter, {name}. Muy bien.',
      '{name}, te ves lista para conquistar el día.',
      'Hoy tienes un aire despierto y favorecedor, {name}.',
    ],
    outfit: [
      '{name}, la combinación que llevas funciona muy bien.',
      'Se nota que pensaste el conjunto, {name}. Buen ojo.',
      '{name}, tu outfit tiene personalidad sin exagerar.',
      'Lo que llevas puesto hoy encaja contigo, {name}.',
      '{name}, has encontrado un equilibrio muy bonito.',
      'Tu ropa de hoy cuenta una historia coherente, {name}.',
      '{name}, el conjunto es moderno y te sienta bien.',
    ],
    styleGeneral: [
      '{name}, el conjunto tiene ritmo y buen gusto.',
      'Hoy tu estilo se siente auténtico, {name}.',
      '{name}, hay coherencia en lo que llevas y se agradece.',
      'Tu look transmite seguridad sin esfuerzo, {name}.',
      '{name}, se nota cuidado en los detalles. Muy bien.',
      'Me gusta la vibra general de tu outfit, {name}.',
    ],
    date: [
      '{name}, vas con un look que invita a sonreír.',
      'Para salir y sentirte bien, {name}, vas ideal.',
      '{name}, tienes ese toque especial sin ir overdressed.',
    ],
    advice: [
      '{name}, un accesorio sencillo podría rematar el look.',
      'Yo mantendría esta línea, {name}. Te define bien.',
      '{name}, con esa base, casi cualquier extra funciona.',
    ],
    styleVibe: [
      '{name}, hoy tu estilo se siente actual y limpio.',
      'Tienes un punto cool sin perder elegancia, {name}.',
      '{name}, tu imagen es clara y con intención.',
    ],
    thanks: [
      '¡De nada, {name}! Me encanta ayudarte.',
      '¡Para eso estoy, {name}! Cuando quieras.',
      '¡Un placer, {name}! Pregunta lo que necesites.',
    ],
    bye: [
      '¡Hasta pronto, {name}! Siempre es un gusto.',
      '¡Nos vemos, {name}! Que tengas un día genial.',
      '¡Chao, {name}! Vuelve cuando quieras un cumplido.',
    ],
    colorAlso: [
      'Además veo un toque de {color} que combina muy bien.',
      'Hay un matiz de {color} que redondea el conjunto.',
      'Noto también {color} y queda muy armónico.',
    ],
  },
  en: {
    compliments: [
      '{name}, you have a natural glow today.',
      'If style had awards, {name}, you would win today.',
      '{name}, your look sends really good vibes.',
      'I love your attitude, {name}. It shows in every detail.',
      '{name}, you wear confidence and it elevates everything.',
      'You are radiating charisma today, {name}.',
      '{name}, your image feels fresh and charming.',
      'You have a lovely effortless touch, {name}.',
      '{name}, you look authentic and that matters.',
      '{name}! Your style speaks for you — and it says great things.',
    ],
    look: [
      '{name}, you have great presence on camera today.',
      'You look relaxed and confident, {name}. It shows.',
      '{name}, your expression matches your outfit really well.',
      'There is harmony in your look today, {name}. I like it.',
      '{name}, you are giving positive energy and it shows.',
      'Your look has character today, {name}. Well done.',
      '{name}, you look ready to own the day.',
      'You have a bright, flattering vibe today, {name}.',
    ],
    outfit: [
      '{name}, the combination you are wearing works really well.',
      'You clearly thought about this outfit, {name}. Great eye.',
      '{name}, your outfit has personality without trying too hard.',
      'What you are wearing fits you today, {name}.',
      '{name}, you found a really nice balance.',
      'Your clothes tell a coherent story today, {name}.',
      '{name}, the outfit is modern and suits you.',
    ],
    styleGeneral: [
      '{name}, the outfit has rhythm and good taste.',
      'Your style feels authentic today, {name}.',
      '{name}, there is coherence in what you are wearing.',
      'Your look feels confident without effort, {name}.',
      '{name}, the details show care. Nicely done.',
      'I like the overall vibe of your outfit, {name}.',
    ],
    date: [
      '{name}, you look inviting and easy to smile at.',
      'For going out and feeling great, {name}, you are spot on.',
      '{name}, you have something special without being overdressed.',
    ],
    advice: [
      '{name}, a simple accessory could finish the look.',
      'I would keep this direction, {name}. It defines you well.',
      '{name}, with this base, almost any accent would work.',
    ],
    styleVibe: [
      '{name}, your style feels current and clean today.',
      'You are cool without losing elegance, {name}.',
      '{name}, your image is clear and intentional.',
    ],
    thanks: [
      "You're welcome, {name}! Happy to help.",
      'Any time, {name}! Just ask.',
      'My pleasure, {name}! Come back whenever.',
    ],
    bye: [
      'See you soon, {name}! Always a pleasure.',
      'Bye, {name}! Have an amazing day.',
      'Later, {name}! Come back for another compliment.',
    ],
    colorAlso: [
      'I also see a touch of {color} that pairs nicely.',
      'There is a hint of {color} rounding off the outfit.',
      'I notice some {color} too — very harmonious.',
    ],
  },
  nl: {
    compliments: [
      '{name}, je hebt vandaag een natuurlijke gloed.',
      'Als stijl prijzen had, {name}, dan won jij vandaag.',
      '{name}, je look straalt echt goede vibes uit.',
      'Ik hou van je houding, {name}. Dat zie je in elk detail.',
      '{name}, je draagt zelfvertrouwen en dat tilt alles op.',
      'Je straalt charisma uit vandaag, {name}.',
      '{name}, je uitstraling voelt fris en charmant.',
      'Je hebt iets moeiteloos moois, {name}.',
      '{name}, je ziet er authentiek uit en dat telt.',
      '{name}! Je stijl spreekt voor je — en het klinkt goed.',
    ],
    look: [
      '{name}, je hebt vandaag veel uitstraling voor de camera.',
      'Je ziet er ontspannen en zelfverzekerd uit, {name}.',
      '{name}, je gezichtsuitdrukking past goed bij je outfit.',
      'Er is harmonie in je look vandaag, {name}. Mooi.',
      '{name}, je geeft positieve energie en dat is te zien.',
      'Je look heeft karakter vandaag, {name}. Goed gedaan.',
      '{name}, je bent klaar om de dag te pakken.',
      'Je hebt een frisse, flatterende vibe vandaag, {name}.',
    ],
    outfit: [
      '{name}, de combinatie die je draagt werkt heel goed.',
      'Je hebt duidelijk nagedacht over dit outfit, {name}.',
      '{name}, je outfit heeft persoonlijkheid zonder te veel.',
      'Wat je draagt past bij je vandaag, {name}.',
      '{name}, je hebt een mooie balans gevonden.',
      'Je kleding vertelt vandaag een coherent verhaal, {name}.',
      '{name}, het outfit is modern en staat je goed.',
    ],
    styleGeneral: [
      '{name}, het outfit heeft ritme en goede smaak.',
      'Je stijl voelt vandaag authentiek, {name}.',
      '{name}, er is samenhang in wat je draagt.',
      'Je look straalt moeiteloos vertrouwen uit, {name}.',
      '{name}, de details tonen zorg. Netjes gedaan.',
      'Ik hou van de algemene vibe van je outfit, {name}.',
    ],
    date: [
      '{name}, je ziet er uitnodigend en spontaan uit.',
      'Om uit te gaan en je goed te voelen, {name}, zit je goed.',
      '{name}, je hebt iets speciaals zonder overdressed te zijn.',
    ],
    advice: [
      '{name}, een simpel accessoire zou de look afmaken.',
      'Ik zou deze lijn aanhouden, {name}. Het past bij je.',
      '{name}, met deze basis werkt bijna elke accent.',
    ],
    styleVibe: [
      '{name}, je stijl voelt vandaag actueel en clean.',
      'Je bent cool zonder elegantie te verliezen, {name}.',
      '{name}, je beeld is helder en met intentie.',
    ],
    thanks: [
      'Graag gedaan, {name}! Ik help je graag.',
      'Altijd welkom, {name}! Vraag maar.',
      'Met plezier, {name}! Kom gerust terug.',
    ],
    bye: [
      'Tot ziens, {name}! Altijd leuk.',
      'Doei, {name}! Fijne dag gewenst.',
      'Later, {name}! Kom terug voor een compliment.',
    ],
    colorAlso: [
      'Ik zie ook een vleugje {color} dat mooi combineert.',
      'Er zit een hint {color} in die het geheel rond maakt.',
      'Ik merk ook {color} op — heel harmonieus.',
    ],
  },
};
