/**
 * Frases extra para más variedad (se combinan con i18n).
 */
const PhrasePools = {
  es: {
    compliments: [
      '{name}, hoy tienes un brillo natural que enamora.',
      'Si el estilo tuviera premio, {name}, tú ganarías hoy.',
      '{name}, hay algo en tu look que transmite buena vibra.',
      'Me encanta tu actitud, {name}. Se nota en cada detalle.',
      '{name}, vas con una seguridad que eleva todo lo que llevas.',
      'Hoy desprendes carisma, {name}. De verdad.',
      '{name}, tu imagen de hoy es fresca y con mucho encanto.',
      'Tienes un punto desenfadado muy bonito, {name}.',
      '{name}, luces auténtica y eso se valora muchísimo.',
      '¡{name}! Tu estilo habla por ti y dice cosas buenas.',
      '{name}, hoy tienes ese algo que hace memorable cualquier look.',
      'Si pudiera votar, {name}, tu estilo ganaría por goleada.',
      '{name}, irradias buen gusto sin pretenderlo. Eso es talento.',
      'Me quedo con tu energía hoy, {name}. Es contagiosa.',
      '{name}, tienes un estilo que abraza sin esfuerzo.',
      'Hoy luces con una seguridad silenciosa muy bonita, {name}.',
    ],
    look: [
      '{name}, hoy tienes muy buena presencia frente a la cámara.',
      'Te ves relajada y segura, {name}. Eso se nota.',
      '{name}, tu expresión acompaña muy bien tu outfit.',
      'Hay armonía en tu imagen hoy, {name}. Me gusta.',
      '{name}, transmites una energía positiva y se ve.',
      'Tu look de hoy tiene carácter, {name}. Muy bien.',
      '{name}, te ves lista para conquistar el día.',
      'Hoy tienes un aire despierto y favorecedor, {name}.',
      '{name}, tu imagen de hoy es clara y muy favorecedora.',
      'Se te ve bien la luz de hoy, {name}. Todo encaja.',
      '{name}, tienes buena cara y eso lo eleva todo.',
      'Tu presencia en cámara es fuerte y amable, {name}.',
      '{name}, hoy transmites calma y eso siempre suma.',
      'Te ves renovada y con ganas, {name}. Se nota un montón.',
    ],
    outfit: [
      '{name}, la combinación que llevas funciona muy bien.',
      'Se nota que pensaste el conjunto, {name}. Buen ojo.',
      '{name}, tu outfit tiene personalidad sin exagerar.',
      'Lo que llevas puesto hoy encaja contigo, {name}.',
      '{name}, has encontrado un equilibrio muy bonito.',
      'Tu ropa de hoy cuenta una historia coherente, {name}.',
      '{name}, el conjunto es moderno y te sienta bien.',
      '{name}, lo que llevas hoy tiene ritmo y buen criterio.',
      'Tu outfit tiene flow, {name}. Me convence totalmente.',
      '{name}, la proporción de tu look es muy acertada.',
      'Hoy vestiste con intención, {name}, y se nota.',
      '{name}, tu ropa y tú estáis en la misma sintonía.',
      'El conjunto es simple pero con chispa, {name}. Me gusta.',
    ],
    styleGeneral: [
      '{name}, el conjunto tiene ritmo y buen gusto.',
      'Hoy tu estilo se siente auténtico, {name}.',
      '{name}, hay coherencia en lo que llevas y se agradece.',
      'Tu look transmite seguridad sin esfuerzo, {name}.',
      '{name}, se nota cuidado en los detalles. Muy bien.',
      'Me gusta la vibra general de tu outfit, {name}.',
      '{name}, hoy tu estilo se siente ligero y seguro.',
      'Hay algo muy "tú" en lo que llevas, {name}.',
      '{name}, tu look no necesita exagerar para destacar.',
      'Se nota personalidad en cada elección, {name}.',
      '{name}, vas cómoda con tu estilo y eso se ve.',
      'Tu imagen de hoy es redonda, {name}. Bien hecho.',
    ],
    neutralLook: [
      'Los neutros te quedan de maravilla hoy, {name}. Muy chic.',
      '{name}, este look sobrio tiene mucha clase.',
      'Paleta neutra y resultado elegante, {name}.',
      '{name}, menos es más y tú lo demuestras.',
      'Los tonos suaves te favorecen muchísimo, {name}.',
    ],
    date: [
      '{name}, vas con un look que invita a sonreír.',
      'Para salir y sentirte bien, {name}, vas ideal.',
      '{name}, tienes ese toque especial sin ir overdressed.',
      '{name}, para una cita vas impecable sin parecer forzada.',
      'Ese look dice "me importo" sin decir demasiado, {name}.',
      '{name}, vas a dejar buena impresión, seguro.',
      'Para quedar tienes el equilibrio perfecto, {name}.',
    ],
    advice: [
      '{name}, un accesorio sencillo podría rematar el look.',
      'Yo mantendría esta línea, {name}. Te define bien.',
      '{name}, con esa base, casi cualquier extra funciona.',
      'Un buen peinado y ya tienes el combo ganador, {name}.',
      '{name}, no cambiaría mucho: vas por buen camino.',
      'Si dudas, quédate con lo que llevas, {name}. Funciona.',
      'Menos capas y más actitud, {name}. Ya lo tienes.',
    ],
    styleVibe: [
      '{name}, hoy tu estilo se siente actual y limpio.',
      'Tienes un punto cool sin perder elegancia, {name}.',
      '{name}, tu imagen es clara y con intención.',
      '{name}, hoy tu estilo es fresco y con carácter.',
      'Tienes un vibe moderno muy atractivo, {name}.',
      '{name}, combinas casual y cuidado a la perfección.',
      'Tu estética de hoy es limpia y con personalidad, {name}.',
    ],
    thanks: [
      '¡De nada, {name}! Me encanta ayudarte.',
      '¡Para eso estoy, {name}! Cuando quieras.',
      '¡Un placer, {name}! Pregunta lo que necesites.',
    ],
    bye: [
      '¡Hasta pronto, {name}! Siempre es un gusto.',
      '¡Nos vemos, {name}! Que tengas un día genial.',
      '¡Chao, {name}! Vuelve cuando quieras un cumplido.',
    ],
    colorAlso: [
      'Además veo un toque de {color} que combina muy bien.',
      'Hay un matiz de {color} que redondea el conjunto.',
      'Noto también {color} y queda muy armónico.',
    ],
    hair: [
      '{name}, tu cabello enmarca el rostro con mucho estilo.',
      '{name}, el peinado de hoy tiene carácter y te favorece.',
      'Me encanta cómo llevas el pelo hoy, {name}.',
      '{name}, tu melena aporta equilibrio a todo el look.',
      'El cabello te queda natural y con presencia, {name}.',
      '{name}, hay algo en tu peinado que redondea la imagen.',
      'Tu pelo luce cuidado y con intención, {name}.',
      '{name}, el peinado combina muy bien con tu outfit.',
      'Hoy el cabello te da un toque especial, {name}.',
      '{name}, el volumen y la forma del peinado están muy bien.',
      'Tu cabello suma frescura al conjunto, {name}.',
      '{name}, el peinado transmite seguridad y buen gusto.',
    ],
    makeup: [
      '{name}, tu maquillaje realza sin recargar.',
      '{name}, el rostro se ve equilibrado y luminoso.',
      'Tu make-up acompaña perfecto tu estilo, {name}.',
      '{name}, los tonos del maquillaje te favorecen mucho.',
      'Hay un toque de color muy acertado, {name}.',
      '{name}, el maquillaje se integra bien con tu look.',
      'Tu rostro luce fresco y cuidado, {name}.',
      '{name}, el maquillaje tiene presencia sin exagerar.',
      'Me gusta cómo resaltas tus rasgos, {name}.',
      '{name}, el acabado del maquillaje es muy elegante.',
      'Tu expresión gana con ese maquillaje, {name}.',
      '{name}, el balance de color en el rostro es impecable.',
    ],
  },
  en: {
    compliments: [
      '{name}, you have a natural glow today.',
      'If style had awards, {name}, you would win today.',
      '{name}, your look sends really good vibes.',
      'I love your attitude, {name}. It shows in every detail.',
      '{name}, you wear confidence and it elevates everything.',
      'You are radiating charisma today, {name}.',
      '{name}, your image feels fresh and charming.',
      'You have a lovely effortless touch, {name}.',
      '{name}, you look authentic and that matters.',
      '{name}! Your style speaks for you — and it says great things.',
      '{name}, you have that something that makes any look memorable.',
      'If I could vote, {name}, your style would win by a landslide.',
      '{name}, you radiate good taste without trying. That is a gift.',
      'I am keeping your energy today, {name}. It is contagious.',
      '{name}, your style feels effortless and warm.',
      'You have a quiet confidence today that looks great, {name}.',
    ],
    look: [
      '{name}, you have great presence on camera today.',
      'You look relaxed and confident, {name}. It shows.',
      '{name}, your expression matches your outfit really well.',
      'There is harmony in your look today, {name}. I like it.',
      '{name}, you are giving positive energy and it shows.',
      'Your look has character today, {name}. Well done.',
      '{name}, you look ready to own the day.',
      'You have a bright, flattering vibe today, {name}.',
      '{name}, your image today is clear and very flattering.',
      'The light suits you today, {name}. Everything clicks.',
      '{name}, you look well-rested and that elevates everything.',
      'Your camera presence is strong and kind, {name}.',
      '{name}, you are giving calm energy and it works.',
      'You look refreshed and motivated, {name}. It really shows.',
    ],
    outfit: [
      '{name}, the combination you are wearing works really well.',
      'You clearly thought about this outfit, {name}. Great eye.',
      '{name}, your outfit has personality without trying too hard.',
      'What you are wearing fits you today, {name}.',
      '{name}, you found a really nice balance.',
      'Your clothes tell a coherent story today, {name}.',
      '{name}, the outfit is modern and suits you.',
      '{name}, what you are wearing today has rhythm and taste.',
      'Your outfit has flow, {name}. I am convinced.',
      '{name}, the proportions of your look are spot on.',
      'You dressed with intention today, {name}, and it shows.',
      '{name}, your clothes and you are in sync.',
      'The outfit is simple but has spark, {name}. I like it.',
    ],
    styleGeneral: [
      '{name}, the outfit has rhythm and good taste.',
      'Your style feels authentic today, {name}.',
      '{name}, there is coherence in what you are wearing.',
      'Your look feels confident without effort, {name}.',
      '{name}, the details show care. Nicely done.',
      'I like the overall vibe of your outfit, {name}.',
      '{name}, your style feels light and confident today.',
      'There is something very "you" in what you are wearing, {name}.',
      '{name}, your look does not need to shout to stand out.',
      'Personality shows in every choice, {name}.',
      '{name}, you look comfortable in your style and it shows.',
      'Your image today feels complete, {name}. Well done.',
    ],
    neutralLook: [
      'Neutrals look wonderful on you today, {name}. Very chic.',
      '{name}, this understated look has real class.',
      'Neutral palette, elegant result, {name}.',
      '{name}, less is more and you prove it.',
      'Soft tones suit you so well, {name}.',
    ],
    date: [
      '{name}, you look inviting and easy to smile at.',
      'For going out and feeling great, {name}, you are spot on.',
      '{name}, you have something special without being overdressed.',
      '{name}, for a date you look polished without trying too hard.',
      'That look says "I care" without saying too much, {name}.',
      '{name}, you will make a great impression, I am sure.',
      'For going out you have the perfect balance, {name}.',
    ],
    advice: [
      '{name}, a simple accessory could finish the look.',
      'I would keep this direction, {name}. It defines you well.',
      '{name}, with this base, almost any accent would work.',
      'A good hair day and you have the winning combo, {name}.',
      '{name}, I would not change much: you are on the right track.',
      'If in doubt, keep what you are wearing, {name}. It works.',
      'Less layering, more attitude, {name}. You already have it.',
    ],
    styleVibe: [
      '{name}, your style feels current and clean today.',
      'You are cool without losing elegance, {name}.',
      '{name}, your image is clear and intentional.',
      '{name}, your style today feels fresh and bold.',
      'You have a very attractive modern vibe, {name}.',
      '{name}, you blend casual and polished perfectly.',
      'Your look today is clean and full of personality, {name}.',
    ],
    thanks: [
      "You're welcome, {name}! Happy to help.",
      'Any time, {name}! Just ask.',
      'My pleasure, {name}! Come back whenever.',
    ],
    bye: [
      'See you soon, {name}! Always a pleasure.',
      'Bye, {name}! Have an amazing day.',
      'Later, {name}! Come back for another compliment.',
    ],
    colorAlso: [
      'I also see a touch of {color} that pairs nicely.',
      'There is a hint of {color} rounding off the outfit.',
      'I notice some {color} too — very harmonious.',
    ],
    hair: [
      '{name}, your hair frames your face with real style.',
      '{name}, your hairstyle has character and suits you today.',
      'I love how you are wearing your hair today, {name}.',
      '{name}, your hair brings balance to the whole look.',
      'Your hair looks natural and confident, {name}.',
      '{name}, something about your hairstyle rounds off the image.',
      'Your hair looks cared for and intentional, {name}.',
      '{name}, the hairstyle pairs really well with your outfit.',
      'Your hair adds a special touch today, {name}.',
      '{name}, the shape and volume of your hair look spot on.',
      'Your hair adds freshness to the look, {name}.',
      '{name}, your hairstyle shows confidence and good taste.',
    ],
    makeup: [
      '{name}, your makeup enhances without overdoing it.',
      '{name}, your face looks balanced and luminous.',
      'Your makeup matches your style perfectly, {name}.',
      '{name}, the makeup tones suit you beautifully.',
      'There is a very well-chosen touch of color, {name}.',
      '{name}, the makeup blends well with your look.',
      'Your face looks fresh and cared for, {name}.',
      '{name}, the makeup has presence without being too much.',
      'I like how you highlight your features, {name}.',
      '{name}, the makeup finish is very elegant.',
      'Your expression wins with that makeup, {name}.',
      '{name}, the color balance on your face is spot on.',
    ],
  },
  nl: typeof NlPhrases !== 'undefined' ? NlPhrases : {},
};
